<?php
/*
 * Copyright © 2023 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php
/** @var $block \SR\Clarity\Block\Clarity */
/** @var $escaper \Magento\Framework\Escaper */
    $clarityCode = $block->getClarityTrackingCode();
    ?>
<?php if ($block->isEnabled()): ?>
    <!-- BEGIN CLARITY TRACKING CODE -->
    <script>
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            <?php if ($block->getCustomerGroup()): ?>
                c.clarity("set", "customer_group", "<?= $escaper->escapeJs($block->getCustomerGroup()) ?>");
            <?php endif;; ?>
            <?php if ($customerEmail = $block->getCustomerEmail()): ?>
                c.clarity("set", "custom-id", "<?= $escaper->escapeJs($customerEmail) ?>");
            <?php endif;; ?>
            <?php if ($orderIncrementId = $block->getOrderId()): ?>
                c.clarity("set", "order_increment_id", "<?= $escaper->escapeJs($orderIncrementId) ?>");
            <?php endif;; ?>
        })(window, document, "clarity", "script", "<?= $escaper->escapeHtml($clarityCode) ?>");
    </script>
    <!-- END CLARITY TRACKING CODE -->
<?php endif; ?>
