<?php
/*
 * Copyright © 2023 Studio Raz. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php
/** @var $block \SR\Clarity\Block\Clarity */
/** @var $escaper \Magento\Framework\Escaper */
$clarityCode = $block->getClarityTrackingCode();
?>
<?php if ($block->isEnabled()): ?>
    <!-- BEGIN CLARITY TRACKING CODE -->
    <script>
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            <?php if ($sessionId = $block->getSessionId()): ?>
                window.srClaritySessionId = '<?= $escaper->escapeJs($sessionId) ?>';
                c.clarity("identify", window.srClaritySessionId, window.srClaritySessionId, '', '');
            <?php endif;; ?>
            <?php if ($orderIncrementId = $block->getOrderId()): ?>
                c.clarity("set", "order-increment-id", "<?= $escaper->escapeJs($orderIncrementId) ?>");
            <?php endif;; ?>
            <?php if ($quoteId = $block->getQuoteId()): ?>
                c.clarity("set", "quote-id", "<?= $escaper->escapeJs($quoteId) ?>");
            <?php endif;; ?>
            <?php if ($customerEmail = $block->getCustomerEmail()): ?>
                c.clarity("set", "customer-email", "<?= $escaper->escapeJs($customerEmail) ?>");
            <?php endif;; ?>
        })(window, document, "clarity", "script", "<?= $escaper->escapeHtml($clarityCode) ?>");


        <?php if ($block->isHyvaTheme()) : ?>
            window.addEventListener("private-content-loaded", function(event) {
                const sectionData = event.detail.data;
                if (sectionData && sectionData.customer) {
                    const customer = sectionData.customer;
                    if (customer && customer.email && window.srClaritySessionId) {
                        let email = customer.email ,
                            fullname = customer.fullname,
                            groupName = customer.groupName;
                        window.clarity("set", "friendly-name", fullname);
                        window.clarity("set", "customer-group", groupName);
                        window.clarity("set", "customer-email", email);
                    }
                }
            });
        <?php else: ?>
            require([
                'Magento_Customer/js/customer-data'
            ], function (customerData) {
                customerData.get('customer').subscribe(function (customer) {
                    if (customer && customer.email && window.srClaritySessionId) {
                        let email = customer.email;
                        let fullname = customer.fullname;
                        let groupName = customer.groupName;
                        window.clarity("set", "friendly-name", fullname);
                        window.clarity("set", "customer-group", groupName);
                        window.clarity("set", "customer-email", email);
                    }
                });
            });
        <?php endif; ?>

    </script>
    <!-- END CLARITY TRACKING CODE -->
<?php endif; ?>
